# Generated by Django 5.0.1 on 2024-01-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='other_benifits',
            new_name='other_benefits',
        ),
    ]
